version: "3.8"
services:
  mlflow:
    image: mlflow
    container_name: mlflow_server
    build:
      context: .
      dockerfile: Dockerfile.mlflow #Optional
    ports:
      - "5001:5001"
    command: mlflow ui --host 0.0.0.0 --port 5001 --backend-store-uri ./mlflow_run/
    volumes:
      - ./mlflow_run:/app/mlflow_run
  api:
    build: .
    container_name: api_server
    ports:
      - "8000:8000"
    depends_on:
      - mlflow
    volumes:
      - ./src:/app
      - ./datos.txt:/app/datos.txt
      - ./models:/app/models

